config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # "" = / -> empty
    # namespace 를 지정할 때 app name이 있어야 한다
    # namespace -> appname ->{% url 'rooms:search' %} 이런식으로 template에서 사용가능
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

# /rooms로 시작하는 url -> room file || start from nothing(home login logout) -> core
app_name = "core"

# 맨 처음 화면에 방들을 보여주고 싶은거니까 room을 import - > home화면에 보여줌
urlpatterns = [
    # HomeView는 class이기떄문에 asview써야함
    # path -> 1.url 2. function
    path("", room_views.Homeview.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

# path에 name을 지정해주면 어느 template에서든 간단하게 url로 연결시킬 수 있다.
urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path, reverse_lazy
from . import views

# config에 있는 url에서 연결 가능하다
app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.conplete_verification, name="complete-verification"
    ),
    path("update_profile", views.UpdateProfileView.as_view(), name="update"),
    path(
        "update_password",
        views.UpdatePasswordView.as_view(success_url=reverse_lazy("core:home")),
        name="password",
    ),
    path("switch-hosting", views.switch_hosting, name="switch-hosting"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500">
    &copy; 2022 Hbnb, Inc. All rights reserved.
</footer>

templates/partials/messages.html
{% if messages %}
<ul class="top-0 absolute mx-auto left-0 right-0 flex justify-center">
    {% for message in messages %}
    <li class="message z-10 font-semibold bg-gray-700 rounded-full text-white py-4 px-6 w-64 text-center {% if message.tags %} {{ message.tags }} {% endif %}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-semibold h-full">
    <!--Django has Context processor that adds info to my templates-->
    <!--Bring cookies and find user and put it to the template authmatically-->
    {% if user.is_authenticated %}
    <li class="nav_link">
        <a href="{% url 'users:switch-hosting' %}">
            {% if request.session.is_hosting %}
            Stop hosting
            {% else %}
            Start hosting
            {% endif %}
        </a>
    </li>
    {% if request.session.is_hosting %}
    <li class="nav_link"><a href="{% url 'rooms:create' %}">Create Room</a></li>
    {% endif %}
    <li class="nav_link"><a href="{{user.get_absolute_url}}">Profile</a></li>
    <li class="nav_link"><a href="{% url 'users:logout' %}">Log Out</a></li>
    {% else %}
    <!-- "users:login"은 template의 users폴더의 login html파일로 링크-->
    <li class="nav_link"><a href="{% url 'users:login' %}">Login</a></li>
    <li class="nav_link"><a href="{% url 'users:signup' %}">Sign up</a></li>
    {% endif %}

</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github-login' %}" class="btn text-center mb-2 text-gray-700 bg-purple-300">
        <i class="fa-brands fa-github  mr-2"></i> Continue with Github
    </a>
    <a href="{% url 'users:kakao-login' %}" class="btn text-center mb-2 text-gray-700 bg-yellow-500">
        <i class="fa-solid fa-comment  mr-2"></i> Continue with Kakao
    </a>
</div>

<div class="flex items-center w-full my-4">
    <div class="h-px w-full bg-gray-500"></div>
    <span class="text-gray-700 font-semibold text-sm mx-4">or</span>
    <div class="h-px w-full bg-gray-500"></div>
</div>