config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # "" = / -> empty
    # namespace 를 지정할 때 app name이 있어야 한다
    # namespace -> appname ->{% url 'rooms:search' %} 이런식으로 template에서 사용가능
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

# /rooms로 시작하는 url -> room file || start from nothing(home login logout) -> core
app_name = "core"

# 맨 처음 화면에 방들을 보여주고 싶은거니까 room을 import - > home화면에 보여줌
urlpatterns = [
    # HomeView는 class이기떄문에 asview써야함
    # path -> 1.url 2. function
    path("", room_views.Homeview.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

# path에 name을 지정해주면 어느 template에서든 간단하게 url로 연결시킬 수 있다.
urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/mixins/room_card.html
<div class="w-1/4 mb-10 px-2 overflow-hidden">
    <a href="{% url 'rooms:detail' room.pk %}">
        <div class="w-full h-64 bg-cover bg-center rounded-lg mb-2" style="background-image: url({{room.first_photo}});"></div>
        <div class="flex justify-between mb-2 truncate">
            <div class="w-4/5 overflow-hidden flex">
                {% if room.host.superhost %}
                <span class="mr-2 uppercase font-semibold text-sm border border-black rounded-md px-1 py-px">superhost</span>
                {% endif %}
                <!-- w-8/12 block truncate 는 텍스트를 생략되어 보이게 한다-->
                <span class="text-sm text-gray-700 block truncate">{{room.city}}, {{room.country.name}}</span>
            </div>
            <span class="text-sm flex items-center">
                <i class="fa-solid fa-star text-xs text-red-500 mr-1"></i> {{room.total_rating}}
            </span>
        </div>
        <span class="text-black">{{room.name}}</span>
    </a>
</div>

templates/mixins/user_avatar.html
{% if user.avatar %}
<div class="{{h_and_w|default:'h-20 w-20'}} rounded-full bg-cover" style="background-image: url({{user.avatar.url}});"></div>
{% else %}
<div class="{{h_and_w|default:'h-20 w-20'}} bg-gray-700 rounded-full text-white flex justify-center items-center overflow-hidden">
    <span class="{{text|default:'text-3xl'}}">{{user.first_name|first}}</span>
</div>
{% endif %}