config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # "" = / -> empty
    # namespace 를 지정할 때 app name이 있어야 한다
    # namespace -> appname ->{% url 'rooms:search' %} 이런식으로 template에서 사용가능
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

# /rooms로 시작하는 url -> room file || start from nothing(home login logout) -> core
app_name = "core"

# 맨 처음 화면에 방들을 보여주고 싶은거니까 room을 import - > home화면에 보여줌
urlpatterns = [
    # HomeView는 class이기떄문에 asview써야함
    # path -> 1.url 2. function
    path("", room_views.Homeview.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

# path에 name을 지정해주면 어느 template에서든 간단하게 url로 연결시킬 수 있다.
urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
# python

# django
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django_countries.fields import CountryField
from cal import Calendar

# third-party
from core import models as core_models

# packages


# 반복되어 사용하는 기능이다. 아이템의 이름을 설정
# roomtype amenity ficility 모두 항목(roomtype)과 아이템들을(hotel, shared, private)가진다
# 그래서 이 아이템들은 공통된 기능을 가지므로 아이템들의 같은 기능을 모은 abstractitem을 만듬
# 이름을 가지고 str = self.name 으로 설정
class AbstractItem(core_models.TimeStampedModel):

    """Abstract Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """RoomType Model Definition"""

    class Meta:
        verbose_name = "Room Type"
        ordering = ["created"]


class Amenity(AbstractItem):

    """Amenity Model Definition"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """Facility Model Definition"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """HouseRule Model Definition"""

    class Meta:
        verbose_name = "House Rule"


# Photo is linked to room and room is linked to user
# class room보다 위에 있기 떄문에 foreignkey("room", on_delete)형식을 사용 (밑으로 내려줘야 하거나)
# 모델들이 많으면 ""으로 string해서 쓰는 것이 좋다.
class Photo(core_models.TimeStampedModel):

    """Photo Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    # 사진은 방에 대한 포린 키를 가진다 - 즉 photos를 통해 방이 가진 모든 사진 확인 가능
    # room.photos.all()
    # 코드를 위에서부터 아래로 읽기 때문에 class Room보다 밑으로 보내야 하지만 "Room"을 쓰면 된다
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """Room Model Definiton"""

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField(help_text="test help text")
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    # user가 relatedname = rooms를 통해 class Room을 찾게 함
    # hyeok.rooms.all()은 hyeok가 가지는 room을 다 볼 수 있다.
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    # relatedname is for target -- users.User or Roomtype
    # 예를 들어 roomtype = hotelroom이라면 hotelroom.rooms.all()를 통해 호텔룸인 룸을 다 볼 수 있다
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    # amenities.rooms, facilities.rooms, house_rules.rooms
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    # view admin 어디에서든 모델을 저장할 때 실행된다
    # 그래서 어드민에서만 뭔가를 저장할 경우를 원할 때를 위해 어드민은 savemodel이라는 method를 가진다
    # savemodel은 어드민을 관리할 수 있다 어느 어드민이 저장을 시도하는지
    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        for review in all_reviews:
            all_ratings += review.rating_average()
        if len(all_reviews) > 0:
            return round(all_ratings / len(all_reviews), 1)
        else:
            return 0

    def first_photo(self):
        # want to get the value of queryset
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        this_month = now.month
        next_month = this_month + 1
        if this_month == 12:
            next_month = 1
        this_month_cal = Calendar(this_year, this_month)
        next_month_cal = Calendar(this_year, next_month)
        return [this_month_cal, next_month_cal]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models

# From Field renders Widget
# Widget is HTML element


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False,
        empty_label="Any kind",
        queryset=models.RoomType.objects.all(),
    )
    # To Do: set max min
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    # overiding save method
    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, UpdateView, FormView, View
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from . import models, forms


# 파이썬 문법을 활용하여 여러 함수들을 생성하고
# 이를 이용하여 자신이 원하는 형태로 데이터를 처리한 뒤, 어떠한 html로 데이터를 보내게 됩니다.

# django는 request를 받으면 view에서 파이썬문법을 이용해 respond함
# 매번 http response를 쓰는 것이 번거롭기 떄문에 template를 render한다
# 템플릿은 파이썬이 compile해주는 html이다
class Homeview(ListView):

    """HomeView Definition"""

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"


# 같은 것을 반복하고 싶지 않고 상속을 사용하고 싶을 떈 class based view 1가지를 잘함
# 복잡한 폼을 쓰거나 여러 요소에 관한 필터링이 있다면 function based view 여러가지 가능
# 복잡한 컨트롤을 하거나 코드를 보고 싶다면 fbv
# 둘 다 더 편리한 상황이 있으므로 선택


class RoomDetail(DetailView):

    """RoomDetail Definition"""

    model = models.Room


class SearchView(View):
    def get(self, request):
        country = request.GET.get("country")

        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():

                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True
                """
                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility
                """

                rooms = models.Room.objects.filter(**filter_args)
                for amenity in amenities:
                    rooms = rooms.filter(amenities=amenity)
                for facility in facilities:
                    rooms = rooms.filter(facilities=facility)

                # qs = models.Room.objects.filter(**filter_args).order_by("-created")
                qs = rooms.order_by("created")

                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)

                return render(
                    request,
                    "rooms/search.html",
                    {"form": form, "rooms": rooms},
                )

        else:
            form = forms.SearchForm()

        return render(
            request,
            "rooms/search.html",
            {"form": form},
        )


class EditRoomView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )
    success_message = "Room Updated"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404
        return room


# 사진 다 지우니까 에러 생긴다  - 해결하기
@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        photo = models.Photo.objects.get(pk=photo_pk)
        if not room.host.pk == user.pk and user.pk == photo.room.pk:
            messages.error(request, "Can't delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Deleted")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = ("caption",)

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


# 리액트 공부해서 drag and drop기능 추가하기
# 방 삭제하는 기능 추가
class AddPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, FormView):

    template_name = "rooms/photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    # save_m2m 은 model을 database에 저장한 후에 사용
    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, "Room Created")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/photo_create.html
{% extends "base.html" %}

{% block page_title %}
Upload Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border-2 p-6 border-gray-500">

    {% include 'mixins/room/room_form.html' with form=form cta="Upload Photo" %}

</div>

{% endblock content %}

templates/rooms/photo_edit.html
{% extends "base.html" %}

{% block page_title %}
Update Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border-2 p-6 border-gray-500">

    {% include 'mixins/room/room_form.html' with form=form cta="Update Photo" %}

</div>

{% endblock content %}

templates/rooms/room_create.html
{% extends "base.html" %}

{% block page_title %}
Create Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border-2 p-6 border-gray-500">

    {% include 'mixins/room/room_form.html' with form=form cta="Create Room" %}

</div>

{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}

{% load is_booked %}

{% block page_title %}
{{room.name}}
{% endblock page_title %}


{% block content %}

<div class="-mt-5 container max-w-full h-75vh mb-20 flex">
    <div class="h-full w-1/2 bg-cover" style="background-image: url({{room.first_photo}});"></div>
    <div class="h-full w-1/2 flex flex-wrap">
        {% for photo in room.get_next_four_photos %}
            <div style="background-image: url({{photo.file.url}});" class="w-1/2 h-auto bg-cover bg-center border border-gray-500"></div>
        {% endfor %}
    </div>
</div>

<div class="container mx-auto flex justify-around pb-56">
    <div class="w-1/2">
        <div class="flex justify-between">
            <div class="mb-5">
                <h4 class="text-3xl font-medium mb-px">{{room.name}}</h4>
                <h4 class="text-gray-700">{{room.city}}</h4>
            </div>
            <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                {% include "mixins/user_avatar.html" with user=room.host %}
                <span class="mt-3 text-gray-600">{{room.host.first_name}}</span>
            </a>
        </div>
        <div class="flex border-section">
            <span class="mr-5 font-light">{{room.room_type}}</span>
            <span class="mr-5 font-light"><i class="far fa-bed-alt"></i> {{room.beds}} bed{{room.beds|pluralize}}</span>
            <span class="mr-5 font-light"><i class="far fa-door-closed"></i> {{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span>
            <span class="mr-5 font-light"><i class="far fa-bath"></i> {{room.baths}} bath{{room.baths|pluralize}}</span>
            <span class="mr-5 font-light"><i class="far fa-user"></i> {{room.guests}} guest{{room.guests|pluralize}}</span>
        </div>
        <p class="border-section">
            {{room.description}}
        </p>
        <div class="border-section">
            <h4 class="font-medium text-lg mb-5">Amenities</h4>
            {% for a in room.amenities.all %}
                <li class="mb-2">{{a}}</li>
            {% endfor %}
        </div>
        <div class="border-section">
            <h4 class="font-medium text-lg mb-5">Facilities</h4>
            {% for f in room.facilities.all %}
                <li class="mb-2">{{f}}</li>
            {% endfor %}
        </div>
        <div class="border-section">
            <h4 class="font-medium text-lg mb-5">House Rules</h4>

            {% if room.house_rules.count == 0 %}
                <li>Have a nice trip <i class="far fa-tree-palm fa-xl"></i></li>
            {% else %}
                {% for r in room.house_rules.all %}
                    <li class="mb-2">{{r}}</li>
                {% endfor %}
            {% endif %}
        </div>
        <div class="mt-10">
            <h4 class="font-medium text-2xl mb-5">Reviews</h4>
            <div class="flex items-center">
                <div class="flex items-center">
                    <i class="fas fa-star text-teal-500 fa-sm mr-1"></i>
                    <span class="font-bold text-xl">{{room.total_rating}}</span>
                </div>
                <div class="h-5 w-px bg-gray-500 mx-5"></div>
                <div>
                    <span class="font-bold text-xl">{{room.reviews.count}}</span>
                    <span>review{{room.reviews.count|pluralize}}</span>
                </div>
            </div>
            <div class="mt-10">
                {% for review in room.reviews.all %}
                <div class="border-section">
                    <div class="mb-3 flex">
                        <div>
                            {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text='xl' %}
                        </div>
                        <div class="flex flex-col ml-5">
                            <span class="font-medium">{{review.user.first_name}}</span>
                            <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                        </div>
                    </div>
                    <p>
                        {{review.review}}
                    </p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="w-1/3">
        {% if room.host == user %}
            <a href="{% url 'rooms:edit' room.pk %}" class="py-3 rounded-lg font-medium text-lg w-full text-center bg-teal-500 text-white block mb-10">Edit Room</a>
            <!--일단 버튼만 만들어 놓음 삭제하는 기능 추가하기-->
            <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">Delete Room</a>
        {% else %}
            {% if not request.session.is_hosting %}
                {% for calendar in room.get_calendars %}
                    <div class="mb-20">
                        <span class="text-center text-lg block mb-8 font-semibold">{{calendar.get_month}} / {{calendar.year}}</span>
                        <div class="grid grid-cols-7 gap-2.5 justify-items-center mb-4 font-semibold">
                            {% for day in calendar.day_names %}
                                <span>{{day}}</span>
                            {% endfor %}
                        </div>
                        <div class="grid grid-cols-7 gap-2.5 justify-items-center font-medium">
                            {% for day in calendar.get_days %}
                                {% is_booked room day as is_booked_bool %}
                                {% if day.number != 0 %}
                                    {% if day.past %}
                                        <span class="rounded bg-gray-200 w-4/5 text-center p-1 mb-2 text-gray-300">{{day}}</span>
                                    {% elif is_booked_bool %}
                                        <span class="rounded bg-gray-200 w-4/5 text-center p-1 mb-2 text-gray-300 line-through">{{day}}</span>
                                    {% else %}
                                        <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}" class="bg-gray-200 w-4/5 text-center rounded text-gray-700 p-1 mb-2 hover:bg-teal-400 hover:text-white cursor-pointer hover:font-semibold">{{day}}</a>
                                    {% endif %}
                                {% else %}
                                    <span></span>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/rooms/room_edit.html
{% extends "base.html" %}

{% block page_title %}
Update Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border-2 p-6 border-gray-500">

    {% include 'mixins/room/room_form.html' with form=form cta="Update Room" %}

    <!--To do: make it interactive with react and js-->
    <div class="mt-4">
        <a href="{% url 'rooms:photos' room.pk %}" class="text-teal-500 font-semibold"><i class="far fa-camera"></i> Edit Photos</a>
    </div>

</div>

{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}


{% block page_title %}
Home
{% endblock page_title %}


{% block content %}

<div class="container mx-auto pb-10">

    <div class="rounded-3xl -mx-40 h-50vh mt-32 mb-20 bg-center" style="background-image: url(https://images.unsplash.com/photo-1646906975349-eebfad38ee3b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1579&q=80);"></div>

    <div class="flex flex-wrap -mx-40 mb-10">
        {% for room in rooms %}
        {% include 'mixins/room_card.html' with room=room %}
        {% endfor %}
    </div>

    <div class="flex items-center justify-center mx-auto container">
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500"><i class="fa-solid fa-arrow-left fa-lg"></i></a>
        {% endif %}

        <span class="mx-3 font-medium text-lg">
            {{page_obj.number}} of {{page_obj.paginator.num_pages}}
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}" class="text-teal-500"><i class="fa-solid fa-arrow-right fa-lg"></i></a>
        {% endif %}

    </div>
</div>

{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}

{% block page_title %}
{{room.name}}'s Photos'
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container mx-auto my-10 flex flex-col">

    <div class="my-10 w-full">
        <a href="{% url 'rooms:add-photo' room.pk %}" class="py-3 rounded-lg font-medium text-lg text-center text-white bg-red-500 w-1/6 block">Upload Photo</a>
    </div>

    {% for photo in room.photos.all %}
    <div class="mb-5 p-6 border border-gray-400 flex justify-between">
        <div class="flex items-start">
            <img src="{{photo.file.url}}" class="w-32 h-32" />
            <span class="ml-5 text-xl">{{photo.caption}}</span>
        </div>
        <div class="flex flex-col w-1/5">
            <a class="py-3 rounded-lg font-medium text-lg w-full text-center text-white mb-5 bg-teal-500" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Edit</a>
            <a class="py-3 rounded-lg font-medium text-lg w-full text-center text-white bg-red-600" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">Delete</a>
        </div>
    </div>
    {% endfor %}
    <div class="flex justify-center mt-5">
        <!-- {% url 'rooms:edit' room.pk %}-->
        <a href="{{room.get_absolute_url}}edit" class="text-teal-500 font-medium text-2xl">Back to edit room</a>
    </div>
</div>

{% endblock content %}

templates/rooms/search.html
<!-- extend를 쓰면 여기있는 것이 base로 간다 -->
{% extends "base.html" %}

{% block page_title %}
Search
{% endblock page_title %}

<!-- 그래서 이것을 비워놓으면 보이지 않게 된다 -->
<!-- 이곳에 따로 form.을 가지고 싶기 때문이다 -->
{% block search-bar %}{% endblock search-bar %}

{% block content %}

<h2>Search</h2>

<form method="get" action="{% url 'rooms:search' %}">
    {{form.as_p}}
    <button>Search</button>
</form>

<h3>Results</h3>


{% for room in rooms %}
<h3>{{room.name}}</h3>
{% endfor %}

<!--To Do make Paginator-->

{% if rooms %}

{% if rooms.has_previous %}
<a href="{{request.get_full_path}}&page={{rooms.previous_page_number}}">Previous</a>
{% endif %}
Page {{rooms.number}} of {{rooms.paginator.num_pages}}
{% if rooms.has_next %}
<a href="{{request.get_full_path}}&page={{rooms.next_page_number}}">Next</a>
{% endif %}

{% endif %}

{% endblock content %}